# Generated by Django 5.2.7 on 2025-11-08 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_bulkresearchsession'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BulkResearchSession',
        ),
    ]
