# Generated by Django 5.2.7 on 2025-11-10 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulk_research', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkresearchsession',
            name='external_session_id',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
